version: '2'
services:
  db:
    build:
      dockerfile: ./db/postgres/Dockerfile
      context: .
    ports:
      - 5433:5432
  web:
    build: .
    volumes:
      - .:/home/projects/challenge/
    depends_on:
      - db
    ports:
      - 8001:8001
#    command: bash -c "cd backend/ ; pip install -r requirements.txt ; python manage.py runserver 0.0.0.0:8001"
    tty: true
